env:
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
rules:
  import/extensions:
    - error
    - ignorePackages
    - ts: never
  no-console: off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
settings:
  import/extensions:
    - .ts
  import/resolver:
    node:
      extensions:
        - .ts
